/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { City } from "./City";
import { CityCountArgs } from "./CityCountArgs";
import { CityFindManyArgs } from "./CityFindManyArgs";
import { CityFindUniqueArgs } from "./CityFindUniqueArgs";
import { CreateCityArgs } from "./CreateCityArgs";
import { UpdateCityArgs } from "./UpdateCityArgs";
import { DeleteCityArgs } from "./DeleteCityArgs";
import { HotelFindManyArgs } from "../../hotel/base/HotelFindManyArgs";
import { Hotel } from "../../hotel/base/Hotel";
import { Country } from "../../country/base/Country";
import { CityService } from "../city.service";
@graphql.Resolver(() => City)
export class CityResolverBase {
  constructor(protected readonly service: CityService) {}

  async _citiesMeta(
    @graphql.Args() args: CityCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [City])
  async cities(@graphql.Args() args: CityFindManyArgs): Promise<City[]> {
    return this.service.cities(args);
  }

  @graphql.Query(() => City, { nullable: true })
  async city(@graphql.Args() args: CityFindUniqueArgs): Promise<City | null> {
    const result = await this.service.city(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => City)
  async createCity(@graphql.Args() args: CreateCityArgs): Promise<City> {
    return await this.service.createCity({
      ...args,
      data: {
        ...args.data,

        country: args.data.country
          ? {
              connect: args.data.country,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => City)
  async updateCity(@graphql.Args() args: UpdateCityArgs): Promise<City | null> {
    try {
      return await this.service.updateCity({
        ...args,
        data: {
          ...args.data,

          country: args.data.country
            ? {
                connect: args.data.country,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => City)
  async deleteCity(@graphql.Args() args: DeleteCityArgs): Promise<City | null> {
    try {
      return await this.service.deleteCity(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Hotel], { name: "hotels" })
  async findHotels(
    @graphql.Parent() parent: City,
    @graphql.Args() args: HotelFindManyArgs
  ): Promise<Hotel[]> {
    const results = await this.service.findHotels(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Country, {
    nullable: true,
    name: "country",
  })
  async getCountry(@graphql.Parent() parent: City): Promise<Country | null> {
    const result = await this.service.getCountry(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
